version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-app
    container_name: next-app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

volumes:
  node_modules:
